### ISSUE TITLE
a bit of criticism.

### ISSUE THREAD

**Issue by r-pv** [Doc-Raptor/dragon_controller#1]
Hi there, I'm thinking for a bit now to build an stm32 controller board too, so if you allow me to put my two cents on your board I think I can give you a little help.

So the first thing it's the mosfet you choose ( HUF76639S3ST ), didn't seems to be adequate for this task, their RDSON seems huge for the task, for the bed you should look for something below 10mΩ, the mosfet that you're using are 27mΩ at 10v, but you'll be using 3.3v for the gate so, if a read correctly the datasheet, you should be getting way higher RSDSON that the advertised 27mΩ and you'll get around 40mΩ, so if you are planing to use this at 24v on a typical 120w bed that'll be around 1W heat on the mosfet, you'll need active cooling (FAN)  and  for a 12v system that's 4W, I think this won't work for much. I'm planning to use the AON6522 or the AON7420, maybe a mix of both.

Next, the switching converter seems too old, you should look for a modern switching converter, after all, you won't be using more than 200mA for this. So for a 24v systems something like the MP1584 or the MP2451 are more than OK, for 12v you can use something like the MP2359.
In the same point, your layout for the switching converter are quite bad, on the datasheet of the IC that you'll be using check for the "layout recommendation" part and duplicate it, literately, big planes and component positions. If you are using a modern switching converter with a layout like you used on this controller it just won't work.

The tracks seems a bit thin, at least for the bed.

Cheers!.

**Comment by Doc-Raptor** [comment]
Thanks for the Tips. I took the mosfet for the bed only for testing in the moment until I find something better. I only got the boards yesterday.
With the switching converter: It is not the newest and overkill, but literary every manufacturer has one in their lineup and it works even on a crued layout if it is under light load, but I will look in to the ones you recommended. 
And I will increase the thickness of some of the tracks, when I finalize the layout and flood the pcb in some places with power and ground

Thanks and have a nice day

**Comment by r-pv** [comment]
So I made a mistake, it's AON7520 (not 7420). If you like the THT mosfets the irlb8743 seems nice too, I'm using a controller with this mosfets and it's OK with 3v3 logic level. But if you can get a "gate driver" will be the best, but are a bit hard to get, at least to me.

Regarding the DC converter, you really should ditch it, not just because it's old, more because its working frequency, 52khz, it'll produce tons of EMI and probably will mess with the ADC readings if not with all, at very least you should add an RC filter after its output. The AMS1117, I used it and liked a lot but requires a lot of capacitance for working properly, I recently ditched it for the RT9013, all the new regulators are smaller, smarter, requires fewer capacitance/inductance and they just work better.

May I ask why you choose the F103RET MCU?, this part it's why I really decide anything, I what a simple controller without too much specs.

Cheers!.

**Comment by Doc-Raptor** [comment]
I will be testing the HY4903B and SE30150. I bought them a few months ago most of them for someone else to safe shipping cost when I bought some PMV40UN2 and some other stuff. They have a RSDSON of 2mΩ when I looked it up two days ago. And they should drop in very easily.

The RT9013 sounds very good. When this board works I will replace the AMS1117 for the RT9013. Also the LM2575 could be replaced.

The F103RET (the f103 series in generaly) overing a lot for a relative low price. The F103RET should have enough memory for the firmware (if not the F103RF and F103RG should drop rigth in without problems). There are other factors, but overall the stm32f103 series overs for the price a lot.

**Comment by r-pv** [comment]
The HY4903B sounds pretty good, at 3V3 seems that you'll get around 8mΩ, the SE30150 _seems_ better but the gate threshold it's at max 3v, too close to the 3V3 voltage, may not work, also, the datasheet didn't included an RDSOn graph to see how much resistance you can expect. Now, if you can get something that be a level shifter (PWM from 3v3 to 5v or 10v), that's another case!, ST has a [3printer board controller](https://www.st.com/en/evaluation-tools/steval-3dp001v1.html) that uses the SN74LVC1G125 as a level shifter, to get 5v PWM (or you can get a proper gate/mosfet driver). With an 5v PWM you will get an RDSOn of 2.1mΩ on the SE30150 and 3mΩ on the HY4903B.

The PMV40UN2 for switching FAN outputs seems pretty good, I'll use the AO34000A, but for this task there's not really any difference.

Cheers.

**Comment by r-pv** [comment]
Hi, now it's looking great, just the layout requires a few details, check the datasheet of the IC: it says that you should put the components as close as possible (specially the capacitors), also, components like the mp2451 and modern switching regulators that work at high frequencies they need a big ground plane (you should use all available space on your pcb as ground plane, normally it's a good practice), I'll post how's the layout that I use and know that really works. The layout it's super important for this type of regulators, I remember that I used a layout like on your previous design for the MP1584, the regulator just give a random output from 50% to 95% of the VIN, it just won't work.

[rSTM32F103RCT6.pdf](https://github.com/Doc-Raptor/dragon_controller/files/4351832/rSTM32F103RCT6.pdf)

![layout0](https://user-images.githubusercontent.com/12518765/77016050-310b4d80-693c-11ea-9d85-b095390c4610.jpg)
